#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytest-flake8
Version  : 1.0.6
Release  : 5
URL      : https://files.pythonhosted.org/packages/3d/4f/dcd73f558ee43d9f83ed0c92eb13fb64c7c96f54606171bfbf8dbac5182b/pytest-flake8-1.0.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/3d/4f/dcd73f558ee43d9f83ed0c92eb13fb64c7c96f54606171bfbf8dbac5182b/pytest-flake8-1.0.6.tar.gz
Summary  : pytest plugin to check FLAKE8 requirements
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pytest-flake8-license = %{version}-%{release}
Requires: pytest-flake8-python = %{version}-%{release}
Requires: pytest-flake8-python3 = %{version}-%{release}
Requires: flake8
Requires: pytest
BuildRequires : buildreq-distutils3
BuildRequires : flake8
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
======================================================

%package license
Summary: license components for the pytest-flake8 package.
Group: Default

%description license
license components for the pytest-flake8 package.


%package python
Summary: python components for the pytest-flake8 package.
Group: Default
Requires: pytest-flake8-python3 = %{version}-%{release}

%description python
python components for the pytest-flake8 package.


%package python3
Summary: python3 components for the pytest-flake8 package.
Group: Default
Requires: python3-core
Provides: pypi(pytest_flake8)
Requires: pypi(flake8)
Requires: pypi(pytest)

%description python3
python3 components for the pytest-flake8 package.


%prep
%setup -q -n pytest-flake8-1.0.6
cd %{_builddir}/pytest-flake8-1.0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589325481
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytest-flake8
cp %{_builddir}/pytest-flake8-1.0.6/LICENSE %{buildroot}/usr/share/package-licenses/pytest-flake8/ce2741b8c1b2d258bba51a44617e1dbce6a3829b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytest-flake8/ce2741b8c1b2d258bba51a44617e1dbce6a3829b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
